# Generated by Django 6.0 on 2025-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('documents', models.CharField(max_length=200)),
            ],
        ),
    ]
